Brought in changes from InfiniteRecharge repo
Team293/Octabot pull request #2
Opened 2021-02-07 17:08 UTC by qiandrewj

### Purpose
The purpose of this pull request was to clean up the code in the Octabot repo so that it was up to date with InfiniteRecharge
### Description

- Edited bracketing
- Replaced Targeting subsystem in Octabot repo with the updated Targeting file from InfiniteRecharge
### Testing
Code builds but is not tested.

2021-02-07 17:10 UTC, bjmcternan reviewed
Looks good. Let's test this before merging it

2021-02-07 17:19 UTC, NotVinnny requested changes
This looks good to me. Built but not tested. Will approve when tested.

Edit: Has been tested. Approved.

2021-02-11 23:46 UTC, bjmcternan commented
@NotVinnny now that the robot is working, please change you review to approved. @qiandrewj once Vincent approves, please merge it in and delete the branch

2021-02-11 23:48 UTC, NotVinnny approved these changes

2021-02-12 00:09 UTC, merged